baseurl = "https://joehs16.github.io/jchweb/"
title = "JOEHSIEH.COM"
author = "Joseph Hsieh"
copyright = "place holder"
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Joe Hsieh"
introDescription = "Wecome to my personal website, where I talk about my projects, my interests, and my passions!"
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
#instagram = "realmattbutton"
#linkedin = "matt-button-2225537"
#twitter = "realmattbutton"
