baseurl = "https://joehs16.github.io/"
title = "JOEHSIEH.COM"
author = "Joseph Hsieh"
copyright = "Copyright 2021, Joseph Hsieh, All rights reserved. Cover Photo by <a href="https://unsplash.com/@actionvance?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">ActionVance</a> on <a href="/@actionvance?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  "
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Joe Hsieh"
introDescription = "Wecome! This is where I discuss projects, interests, and my passions"
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
#instagram = "realmattbutton"
#linkedin = "matt-button-2225537"
#twitter = "realmattbutton"
